name: Test

on:
  pull_request: {}
  push:
    branches:
    - master

jobs:
  linux_test:
    name: Linux
    runs-on: ubuntu-latest

    services:
      nats:
        image: ripienaar/testing.go
        ports:
          - 4222:4222

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build
        run: dotnet build -c Release

      - name: Test
        run: dotnet test -c Release --no-build --logger:"console;verbosity=normal"
